### PR TITLE
[Review] Desktop View

### PR DESCRIPTION
**Pull request by dfosco**
image

 - [x] Search bar
 - [x] Suggestion box
    - [x] Correct styles for desktop
    - [x] Correct closing behavior for suggestion box
    - [x] Bug when showing up suggestion on desktop (https://github.com/vtex-apps/search-bar/issues/18)

@tamorim For this to work properly we need to change the behavior of the search icon button on desktop — but I guess that's a change to be done on the theme, right?

### CODE REVIEW

**Comment by tamorim** [comment]
@dfosco Yup, I believe so!

**Comment by dfosco** [comment]
Merged manually by @tamorim

**Comment by dfosco** [comment]
oopsie

**Comment by dfosco** [comment]
@tamorim Please review :dancer:

**Pull request merged**
